name: CI - Build with code analysis for PRs on main

on:
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Build with code analysis
      run: dotnet build -warnaserror ContosoOutdoors.sqlproj /p:RunSqlCodeAnalysis=true
      working-directory: ContosoOutdoors
